include mime.types;

log_format json_analytics escape=json '{'
    '"time": "$time_iso8601", '
    '"remote_addr": "$remote_addr", '
    '"request_id": "$request_id", ' 
    '"status": $status, '
    '"body_bytes_sent": $body_bytes_sent, '
    '"request_time": "$request_time", '
    '"method": "$request_method", '
    '"uri": "$request_uri", '
    '"user_agent": "$http_user_agent"'
'}';

access_log /var/log/nginx/access.log json_analytics;

server {
    listen 80;

    # FRONTEND (Vue)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }

    # BACKEND (FastAPI)
    location /api/ {
        proxy_pass http://backend:8000/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Request-ID $request_id;
        add_header X-Request-ID $request_id;
    }
}

server {
    listen 8081;

    location /metrics {
        stub_status on;
        access_log off;
        allow 127.0.0.1;
        allow 172.16.0.0/12;
        deny all;
    }
}