data_sources:
      - name: mdg_food_price.csv
        url: https://data.humdata.org/dataset/86173d84-f1b5-4470-afb9-5ee56747f4cd/resource/8fc13d1e-abac-4262-8caa-edab795661e6/download/wfp_food_prices_mdg.csv
        format: csv
      - name: global_fuel_price.xlsx
        url: https://datacatalogfiles.worldbank.org/ddh-published/0066829/DR0095290/Global_Fuel_Prices_Database.xlsx
        format: xlsx
      - name: worldbank_commodity_price.xlsx
        url: https://thedocs.worldbank.org/en/doc/74e8be41ceb20fa0da750cda2f6b9e4e-0050012026/related/CMO-Historical-Data-Monthly.xlsx
        format: xlsx
data_destination:
    ingestion: data/data_lake
    cleaning: data/data_warehouse