services:
  backend:
    image: bearisoa/rice-price-pred-backend:latest
    networks:
      - default
      - prometheus_monitoring
    container_name: backend
    expose:
      - "8000"
    restart: always
  
  frontend:
    image: bearisoa/rice-price-pred-frontend:latest
    networks:
      - default
      - prometheus_monitoring
    container_name: frontend-n-proxy
    ports:
      - "80:80"
      - "8081:8081"
    restart: always
    depends_on:
    - backend

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    networks:
      - prometheus_monitoring
    command:
      - -nginx.scrape-uri=http://frontend-n-proxy:8081/metrics
    container_name: nginx-exporter
    ports:
      - "9113:9113"
    restart: always
    depends_on:
      - frontend

networks:
  default:
  prometheus_monitoring:
    external: true 