services:
  backend:
    build: 
      context: ./backend
      tags:
        - bearisoa/rice-price-pred-backend:1.0.0
    image: bearisoa/rice-price-pred-backend:latest
    container_name: backend
    expose:
      - "8000"
    restart: always
  
  frontend:
    build: 
      context: ./frontend
      tags:
        - bearisoa/rice-price-pred-frontend:1.0.0
      args:
        VITE_API_URL: /api
    image: bearisoa/rice-price-pred-frontend:latest
    container_name: frontend-n-proxy
    ports:
      - "80:80"
    restart: always
    depends_on:
    - backend