services:
  backend:
    image: bearisoa/rice-price-pred-backend:latest
    networks:
      - default
      - prometheus_monitoring
    container_name: backend
    expose:
      - "8000"
    restart: always
  
  frontend:
    image: bearisoa/rice-price-pred-frontend:latest
    networks:
      - default
      - prometheus_monitoring
    container_name: frontend-n-proxy
    ports:
      - "80:80"
      - "8081:8081"
    restart: always
    depends_on:
    - backend

networks:
  default:
  prometheus_monitoring:
    external: true