name: Add loki and promtail to prometheus monitoring.

on:
  workflow_dispatch:

jobs:
  Add_loki_n_promtail:
    runs-on: vm-prod
    steps:
      - name: Download promtail and loki Config files
        run: |
          wget https://github.com/RandrianantenainaBearisoa/rice_price_predict/raw/refs/heads/main/loki-config.yaml
          wget https://github.com/RandrianantenainaBearisoa/rice_price_predict/raw/refs/heads/main/promtail-config.yaml
          wget https://github.com/RandrianantenainaBearisoa/rice_price_predict/raw/refs/heads/main/docker-compose-loki-promtail.yml
      - name: Run docker compose
        run: |
          cd $HOME/loki-promtail
          docker compose up -d