name: Continuous Delivery Workflow

on:
  push:
    branches:
      - prod

jobs:
  Check_what_to_do:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: List modified files
        # run: |
        #   for file in ${{ steps.changed-files.outputs.modified_files }}; do
        #     echo "$file was modified"
        #   done
        run: |
          modified=()
          for file in ${{ steps.changed-files.outputs.modified_files}}; do
            top_level="${file%%/*}"
            modified+=("$top_level")
          done
          unique_dirs=($(echo "${modified[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
          echo "Modified files: ${unique_dirs[@]}"