name: Continuous Delivery Workflow

on:
  push:
    branches:
      - prod

jobs:
  Check_what_to_do:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: List modified files
        run: |
          modified=()
          for file in ${{ steps.changed-files.outputs.modified_files}}; do
            top_level="${file%%/*}"
            modified+=("$top_level")
          done
          directories=($(echo "${modified[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
          declare -i scenario=0
          for dir in "${directories[@]}"; do
            if [[ "$dir" == "frontend" ]]; then
                scenario=scenario+1
            fi
            if [[ "$dir" == "backend" ]]; then
                scenario=scenario+2
            fi
          done
          echo "scenario=$scenario" >> $GITHUB_OUTPUT
          echo "Scenario: $scenario"
  Build_and_Push:
    strategy:
      matrix:
        builds: ["0", "frontend", "backend", ""]
    needs: Check_what_to_do
    runs-on: ubuntu-latest
    if: needs.Check_what_to_do.outputs.scenario != '0'
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and Push Image
        run: |
          echo "${{ needs.Check_what_to_do.outputs.scenario }}"