name: Continuous Delivery Workflow

on:
  push:
    branches:
      - prod

jobs:
  Check_what_to_do:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check what to do
        run: git diff --name-only | cut -d/ -f1 | uniq