name: Rollback to a Stable tagged Version # requires a tag to be created in the registry beforehand

on:
  workflow_dispatch:

jobs:
  Rollback:
    runs-on: vm-prod
    steps:
      - name: Tell the server to rollback.
        # echo $HOME/rice-price-predict/rollback.sh
        run: |
          if [ -f "$HOME/rice-price-predict/rollback.sh" ]; then
              echo "File exists."
          fi
